const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
const ui={level:$('#wave'),crowd:$('#score'),timer:$('#timer'),coins:$('#coins'),progress:$('#hp'),boss:$('#boss'),bossBar:$('#boss i')};
const images={};['gun1','gun2','gun3','tank','reactor','monsterClawBig','monsterRockBig','monsterEyeBig','monsterSlimeBig'].forEach(n=>{images[n]=new Image();images[n].src=`assets/${n}.png`});
let W=0,H=0,D=1,last=0,state=null,difficulty='normal',pointer={x:0,down:false};
const modes={easy:{enemy:1,boss:1,speed:.9,rate:1,label:'FACILE'},normal:{enemy:1.55,boss:1.8,speed:1.25,rate:.88,label:'NORMALE'},hard:{enemy:2.25,boss:2.8,speed:1.65,rate:.74,label:'DIFFICILE'}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a);
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*D;canvas.height=H*D;ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
function point(e){const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)*W/r.width}canvas.onpointerdown=e=>{pointer.down=true;point(e);canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=point;canvas.onpointerup=canvas.onpointercancel=()=>pointer.down=false;
addEventListener('keydown',e=>{if(!state)return;if(['ArrowLeft','KeyA'].includes(e.code))pointer.x=state.cannon.x-80;if(['ArrowRight','KeyD'].includes(e.code))pointer.x=state.cannon.x+80});
function reset(level=1){const w=Math.min(W*.86,620),left=(W-w)/2,m=modes[difficulty];state={running:true,won:false,level,difficulty,coins:0,time:0,minDuration:60,reinforce:7,baseHp:100,road:{left,right:left+w,w},cannon:{x:W/2,y:H-72,cool:0,rate:.105/m.rate,damage:1,weapon:0},units:[],enemies:[],particles:[],texts:[],gates:[],crates:[],spawned:0,maxSpawn:9999,boss:null,progress:0,scroll:0,phase:'deploy'};pointer.x=W/2;makeGates();makeCrates();makeArmy();updateUI()}
function makeGates(){const r=state.road,gap=10,gw=(r.w-gap*3)/2,rows=[H*.69,H*.51,H*.34],options=[[{kind:'add',value:8+state.level},{kind:'add',value:14+state.level*2}],[{kind:'add',value:18+state.level*2},{kind:'add',value:28+state.level*3}],[{kind:'add',value:38+state.level*3},{kind:'mul',value:2}]];state.gates=[];rows.forEach((y,row)=>options[row].forEach((g,i)=>state.gates.push({...g,id:`${row}-${i}`,x:r.left+gap+i*(gw+gap),y,w:gw,h:48,used:false}))) }
function makeCrates(){const r=state.road,rewards=[{name:'ARMA',kind:'weapon'},{name:'UNITÀ +30',kind:'units'},{name:'DANNO ×2',kind:'damage'}];state.crates=rewards.map((reward,i)=>{const hp=28+i*16+state.level*5;return{x:r.left+r.w*(i%2?.7:.3),y:H*(.61-i*.19),w:62,h:52,hp,max:hp,reward,dead:false,hit:0}})}
function makeArmy(){const m=modes[difficulty],count=Math.round((42+state.level*12)*m.enemy);for(let i=0;i<count;i++){const row=Math.floor(i/10),col=i%10;state.enemies.push({x:W/2+(col-4.5)*13+rnd(-3,3),y:145-row*12+rnd(-3,3),r:5.3,phase:rnd(0,6.28),speed:rnd(21,36)*m.speed})}const types=['monsterClawBig','monsterRockBig','monsterEyeBig','monsterSlimeBig'],hp=Math.round((75+state.level*26)*m.boss),total=1+Math.floor((state.level-1)/2);state.boss={x:W/2,y:-65,r:34,hp,max:hp,type:types[(state.level-1)%4],hit:0,speed:(18+state.level*1.5)*m.speed,phase:0,active:false,remaining:total,total,index:1}}
function reinforce(){const m=modes[difficulty],count=Math.round((14+state.level*4)*m.enemy);for(let i=0;i<count;i++)state.enemies.push({x:W/2+rnd(-85,85),y:rnd(82,120),r:5.3,phase:rnd(0,6.28),speed:rnd(27,45)*m.speed});text(W/2,150,'RINFORZI NEMICI!','#ff4055');burst(W/2,125,'#ff3048',18)}
function nextBoss(){const b=state.boss,types=['monsterClawBig','monsterRockBig','monsterEyeBig','monsterSlimeBig'];b.remaining--;b.index++;b.type=types[(state.level+b.index-2)%4];b.hp=b.max=Math.round(b.max*1.18);b.x=W/2;b.y=-65;b.hit=0;b.active=true;text(W/2,125,`BOSS ${b.index}/${b.total}`,'#ffdf35');burst(W/2,70,'#ffad20',35)}
function addUnit(x,y){if(state.units.length<650)state.units.push({x:x+rnd(-3,3),y:y+rnd(-2,2),r:5.2,vx:rnd(-12,12),passed:{},crates:{},phase:rnd(0,6.28)})}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)state.particles.push({x,y,vx:rnd(-110,110),vy:rnd(-120,60),life:rnd(.3,.8),max:.8,color,r:rnd(2,5)})}
function text(x,y,value,color='#fff'){state.texts.push({x,y,value,color,life:1,max:1})}
function reward(box){const c=state.cannon;if(box.reward.kind==='weapon'){c.weapon=Math.min(2,c.weapon+1);c.rate*=.72}else if(box.reward.kind==='units'){for(let i=0;i<30;i++)addUnit(box.x+rnd(-25,25),box.y+rnd(10,35))}else if(box.reward.kind==='damage')c.damage*=2;state.coins+=15;text(box.x,box.y-32,`${box.reward.name} SBLOCCATO!`,'#fff34d');burst(box.x,box.y,'#ffcc32',35)}
function useGate(g,entrants){if(g.used||!entrants.length)return;g.used=true;const originals=[...state.units],amount=g.kind==='mul'?Math.min(originals.length*(g.value-1),180):g.value;for(let i=0;i<amount;i++){const u=originals[i%originals.length];addUnit(u.x+rnd(-18,18),u.y+rnd(4,28))}text(g.x+g.w/2,g.y-12,`+${amount}`,'#ffef46');burst(g.x+g.w/2,g.y+g.h/2,'#55ecff',24)}
function update(dt){if(!state?.running)return;state.time+=dt;state.scroll=(state.scroll+190*dt)%70;const r=state.road,c=state.cannon,b=state.boss;if(state.time>=state.minDuration&&!b.active){b.active=true;text(W/2,125,'IL BOSS È ARRIVATO!','#ffcf28');burst(W/2,70,'#ff6b20',45)}c.x+=(clamp(pointer.x,r.left+34,r.right-34)-c.x)*Math.min(1,dt*(pointer.down?14:6));c.cool-=dt;if(state.spawned<state.maxSpawn&&c.cool<=0){addUnit(c.x,c.y-34);state.spawned++;c.cool=c.rate}if(state.time>=state.reinforce&&state.time<state.minDuration){reinforce();state.reinforce+=7}
 const speed=state.phase==='deploy'?216:288;for(const u of state.units){u.y-=speed*dt;if(!b.active&&u.y<H*.42)u.y=H*.42+rnd(0,14);u.x+=clamp((W/2-u.x)*.18+u.vx,-126,126)*dt;u.vx*=.98;u.x=clamp(u.x,r.left+10,r.right-10)}
 for(const g of state.gates){const hit=state.units.filter(u=>!u.passed[g.id]&&u.y<g.y+g.h&&u.y>g.y-10&&u.x>=g.x&&u.x<=g.x+g.w);hit.forEach(u=>u.passed[g.id]=true);useGate(g,hit)}
 for(const box of state.crates){if(box.dead)continue;box.hit-=dt;for(const u of state.units){const key=state.crates.indexOf(box);if(u.crates[key]||Math.abs(u.x-box.x)>box.w*.58||Math.abs(u.y-box.y)>box.h*.58)continue;u.crates[key]=true;box.hp-=c.damage;box.hit=.12;u.y+=18;u.vx+=rnd(-25,25);burst(u.x,u.y,'#ffd34d',2)}if(box.hp<=0){box.dead=true;reward(box)}}
 for(const e of state.enemies){e.y+=e.speed*dt;e.x+=Math.sin(state.time*8+e.phase)*10*dt}const breached=state.enemies.filter(e=>e.y>state.cannon.y-45);if(breached.length){state.baseHp-=breached.length*5;state.enemies=state.enemies.filter(e=>e.y<=state.cannon.y-45);burst(state.cannon.x,state.cannon.y-35,'#ff3048',breached.length*3)}if(b.active){b.y=Math.min(H*.29,b.y+b.speed*dt);b.x=W/2+Math.sin(state.time*1.7)*18}b.phase+=dt;b.hit-=dt;
 const deadU=new Set(),deadE=new Set();for(let i=0;i<state.units.length;i++){const u=state.units[i];let best=-1,bd=15;for(let j=0;j<state.enemies.length;j++){if(deadE.has(j))continue;const e=state.enemies[j],d=Math.hypot(u.x-e.x,u.y-e.y);if(d<bd){bd=d;best=j}}if(best>=0){deadU.add(i);deadE.add(best);burst(u.x,u.y,'#fff',3)}}state.units=state.units.filter((_,i)=>!deadU.has(i));state.enemies=state.enemies.filter((_,i)=>!deadE.has(i));
 let hitters=0;state.units=state.units.filter(u=>{if(b.active&&Math.hypot(u.x-b.x,u.y-b.y)<b.r+10){hitters++;return false}return u.y>-20});if(hitters){b.hp-=hitters*3*c.damage;b.hit=.12;burst(b.x,b.y+15,'#57dfff',hitters*2);text(b.x,b.y+54,`-${hitters*3*c.damage}`)}
 if(b.active&&b.hp<=0){if(b.remaining>1)nextBoss();else{state.running=false;state.won=true;state.coins+=50+state.level*10;burst(b.x,b.y,'#ffd93d',60);setTimeout(()=>finish(true),500)}}else if(state.time>=state.minDuration&&(state.baseHp<=0||b.active&&b.y>state.cannon.y-90)){state.running=false;setTimeout(()=>finish(false),350)}
 for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=140*dt;p.life-=dt}state.particles=state.particles.filter(p=>p.life>0);for(const t of state.texts){t.y-=28*dt;t.life-=dt}state.texts=state.texts.filter(t=>t.life>0);state.progress=clamp(1-(state.enemies.length+b.hp/3)/(43+state.level*9),0,1);updateUI()}
function updateUI(){if(!state)return;const remain=Math.max(0,Math.ceil(state.minDuration-state.time)),b=state.boss;ui.level.textContent=`LIVELLO ${state.level} · ${modes[state.difficulty].label}`;ui.crowd.textContent=`FOLLA ${state.units.length} · BASE ${Math.max(0,state.baseHp)}%`;ui.timer.textContent=`00:${String(remain).padStart(2,'0')}`;ui.timer.style.color=remain<=10?'#ff4055':'#fff';ui.coins.textContent=`★ ${state.coins}`;ui.progress.style.width=`${Math.min(1,state.time/state.minDuration)*100}%`;ui.boss.classList.toggle('hidden',!b.active);if(b.active){$('#boss b').textContent=`BOSS ${b.index}/${b.total}`;ui.bossBar.style.width=`${Math.max(0,b.hp/b.max*100)}%`}}
function road(){const r=state?.road||{left:W*.15,right:W*.85};const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#61caff');sky.addColorStop(.48,'#d9f5ff');sky.addColorStop(.49,'#79c9ed');sky.addColorStop(1,'#3680ba');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#edf2f5';ctx.beginPath();ctx.moveTo(r.left+45,0);ctx.lineTo(r.right-45,0);ctx.lineTo(r.right,H);ctx.lineTo(r.left,H);ctx.closePath();ctx.fill();ctx.strokeStyle='#c5cfd6';ctx.lineWidth=3;for(let y=-70+(state?.scroll||0);y<H;y+=70){ctx.beginPath();ctx.moveTo(r.left+(H-y)*.055,y);ctx.lineTo(r.right-(H-y)*.055,y);ctx.stroke()}ctx.fillStyle='#46515d';ctx.beginPath();ctx.moveTo(r.left+35,0);ctx.lineTo(r.left,H);ctx.lineTo(r.left-24,H);ctx.lineTo(r.left+20,0);ctx.fill();ctx.beginPath();ctx.moveTo(r.right-35,0);ctx.lineTo(r.right,H);ctx.lineTo(r.right+24,H);ctx.lineTo(r.right-20,0);ctx.fill()}
function unit(u,red=false){const s=.72+u.y/H*.45,walk=Math.sin(state.time*13+u.phase)*3,light=red?'#ff6670':'#67d8ff',dark=red?'#790817':'#004caa',base=red?'#ee1730':'#078dff';ctx.save();ctx.translate(u.x,u.y);ctx.scale(s,s);ctx.fillStyle='#08233a55';ctx.beginPath();ctx.ellipse(0,8,7,3,0,0,7);ctx.fill();ctx.strokeStyle=dark;ctx.lineWidth=2.2;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-2,3);ctx.lineTo(-3-walk*.35,10);ctx.moveTo(2,3);ctx.lineTo(3+walk*.35,10);ctx.moveTo(-3,-1);ctx.lineTo(-7-walk*.45,4);ctx.moveTo(3,-1);ctx.lineTo(7+walk*.45,4);ctx.stroke();const body=ctx.createLinearGradient(-4,-4,5,6);body.addColorStop(0,light);body.addColorStop(.42,base);body.addColorStop(1,dark);ctx.fillStyle=body;ctx.beginPath();ctx.roundRect(-4,-3,8,10,3);ctx.fill();ctx.stroke();const head=ctx.createRadialGradient(-2,-8,1,0,-6,6);head.addColorStop(0,'#fff');head.addColorStop(.2,light);head.addColorStop(.7,base);head.addColorStop(1,dark);ctx.fillStyle=head;ctx.beginPath();ctx.arc(0,-7,5,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#fff9';ctx.beginPath();ctx.arc(-1.5,-8.5,1.2,0,7);ctx.fill();ctx.restore()}
function round(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function gate(g){ctx.save();ctx.globalAlpha=g.used?.3:1;ctx.shadowBlur=18;ctx.shadowColor='#00bfff';const grad=ctx.createLinearGradient(0,g.y,0,g.y+g.h);grad.addColorStop(0,'#2be9ff');grad.addColorStop(1,'#0879ff');ctx.fillStyle=grad;round(g.x,g.y,g.w,g.h,10);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font=`900 ${Math.min(34,g.w*.25)}px Rajdhani`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(g.kind==='mul'?`×${g.value}`:`+${g.value}`,g.x+g.w/2,g.y+g.h/2);ctx.restore()}
function crate(box){if(box.dead)return;ctx.save();ctx.translate(box.x,box.y);ctx.fillStyle='#29334288';ctx.beginPath();ctx.ellipse(0,box.h*.48,box.w*.56,10,0,0,7);ctx.fill();ctx.fillStyle=box.hit>0?'#fff':'#e88b19';round(-box.w/2,-box.h/2,box.w,box.h,7);ctx.fill();ctx.strokeStyle='#713600';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#ffcc39';ctx.fillRect(-box.w/2+6,-5,box.w-12,10);ctx.fillStyle='#5b2700';ctx.font='900 21px Rajdhani';ctx.textAlign='center';ctx.fillText(Math.max(0,Math.ceil(box.hp)),0,7);ctx.fillStyle='#fff';ctx.font='900 11px Rajdhani';ctx.fillText(box.reward.name,0,-box.h/2-29);const icon=box.reward.kind==='weapon'?'🔫':box.reward.kind==='damage'?'⚡':'👥';ctx.font='22px sans-serif';ctx.fillText(icon,0,-box.h/2-9);ctx.restore()}
function sprite(im,x,y,size,rot=0){if(!im?.complete)return;ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.drawImage(im,-size/2,-size/2,size,size);ctx.restore()}
function draw(){road();if(!state)return;const b=state.boss;ctx.fillStyle='#ffae00';round(W/2-55,8,110,78,14);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.stroke();if(!b.active){ctx.fillStyle='#fff';ctx.font='900 42px Rajdhani';ctx.textAlign='center';ctx.fillText('?',W/2,61)}if(b.active){ctx.fillStyle='#17203355';ctx.beginPath();ctx.ellipse(b.x,b.y+30,38,11,0,0,7);ctx.fill();const bossBob=Math.sin(state.time*5)*4,bossTilt=Math.sin(state.time*3)*.045;sprite(images[b.type],b.x,b.y+bossBob,b.hit>0?88:80,bossTilt)}state.enemies.forEach(e=>unit(e,true));state.gates.forEach(gate);state.crates.forEach(crate);state.units.forEach(u=>unit(u));ctx.save();ctx.translate(state.cannon.x,state.cannon.y);ctx.fillStyle='#06396a';ctx.beginPath();ctx.arc(0,18,38,0,7);ctx.fill();ctx.strokeStyle='#50eaff';ctx.lineWidth=5;ctx.stroke();ctx.restore();sprite(images[['gun1','gun2','gun3'][state.cannon.weapon]],state.cannon.x,state.cannon.y-4,78,-Math.PI/2);ctx.fillStyle='#081b34dd';round(state.cannon.x-38,state.cannon.y+26,76,25,10);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 15px Rajdhani';ctx.textAlign='center';ctx.fillText(`ARMA LV.${state.cannon.weapon+1}`,state.cannon.x,state.cannon.y+44);for(const p of state.particles){ctx.globalAlpha=p.life/p.max;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()}for(const t of state.texts){ctx.globalAlpha=t.life/t.max;ctx.fillStyle=t.color;ctx.font='900 25px Rajdhani';ctx.fillText(t.value,t.x,t.y)}ctx.globalAlpha=1}
function finish(won){const end=$('#end');$('#end small').textContent=won?'BASE CONQUISTATA':'ESERCITO ESAURITO';$('#end h1').innerHTML=won?'VITTORIA!':'RIPROVA';$('#result').textContent=won?`Hai sconfitto il boss del livello ${state.level}. La prossima battaglia sarà più difficile.`:'Scegli il portale migliore e crea una folla abbastanza grande da superare l’esercito rosso.';$('#again').textContent=won?'LIVELLO SUCCESSIVO':'RIPETI LIVELLO';end.classList.remove('hidden')}
function start(next=false){$('#start').classList.add('hidden');$('#end').classList.add('hidden');reset(next&&state?.won?state.level+1:(state?.level||1))}document.querySelectorAll('[data-difficulty]').forEach(button=>button.onclick=()=>{difficulty=button.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(b=>b.classList.toggle('active',b===button))});$('#play').onclick=()=>start(false);$('#again').onclick=()=>start(true);function loop(t){const dt=Math.min(.032,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
