const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui={wave:document.querySelector('#wave'),score:document.querySelector('#score'),coins:document.querySelector('#coins'),hp:document.querySelector('#hp'),boss:document.querySelector('#boss'),bossBar:document.querySelector('#boss i')};
const files=['player','soldierRed','ally','mech','tank','gun1','gun2','gun3','monsterSlime','monsterSlimeBig','monsterRock','monsterRockBig','monsterEye','monsterEyeBig','monsterClaw','monsterClawBig','turret','portal','barrier','reactor','coin'];
const img={}; files.forEach(n=>{img[n]=new Image();img[n].src=`assets/${n}.png`});
let W,H,dpr,game=null,last=0,keys={},mouse={x:0,y:0,down:false};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('pointermove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});canvas.addEventListener('pointerdown',()=>mouse.down=true);addEventListener('pointerup',()=>mouse.down=false);
const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function sprite(o,im,size=o.r*2.4,rot=0){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(rot);ctx.drawImage(im,-size/2,-size/2,size,size);ctx.restore()}
function reset(){game={running:true,t:0,wave:1,score:0,coins:0,kills:0,nextWave:18,spawn:0,shake:0,flash:0,player:{x:W*.5,y:H*.62,r:27,hp:100,max:100,speed:260,shot:0,pulse:0},enemies:[],bullets:[],particles:[],drops:[],allies:[],turrets:[]};game.allies.push({x:W*.34,y:H*.72,r:22,shot:.2,hp:80,max:80,type:'soldierRed'}, {x:W*.66,y:H*.72,r:24,shot:.6,hp:100,max:100,type:'mech'});game.turrets.push({x:100,y:H-120,r:38,shot:0}, {x:W-100,y:H-120,r:38,shot:.4});updateUI()}
function enemyType(){let pool=['monsterSlime','monsterRock','monsterClaw'];if(game.wave>2)pool.push('monsterEye');if(game.wave>4)pool.push('monsterRock','monsterClaw');return pool[Math.floor(Math.random()*pool.length)]}
function spawn(boss=false){let edge=Math.floor(Math.random()*3),x=edge===0?rnd(30,W-30):edge===1?25:W-25,y=edge===0?-40:rnd(40,H*.65);let type=boss?['monsterSlimeBig','monsterRockBig','monsterEyeBig','monsterClawBig'][Math.floor((game.wave-1)/3)%4]:enemyType();let base=boss?520+game.wave*80:32+game.wave*6;game.enemies.push({x,y,r:boss?65:rnd(24,34),hp:base,max:base,speed:boss?42:rnd(48,76)+game.wave*2,type,boss,hit:0,attack:0})}
function shoot(owner,target,ally=true){let a=Math.atan2(target.y-owner.y,target.x-owner.x),speed=ally?650:310;game.bullets.push({x:owner.x,y:owner.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:ally?5:7,life:1.5,ally,damage:ally?(owner===game.player?18:12):10});if(ally)burst(owner.x+Math.cos(a)*25,owner.y+Math.sin(a)*25,'#4ef4ff',3)}
function burst(x,y,color,n=8){for(let i=0;i<n;i++)game.particles.push({x,y,vx:rnd(-140,140),vy:rnd(-140,140),life:rnd(.25,.65),max:.65,color,r:rnd(2,6)})}
function nearest(o){let best=null,bd=Infinity;for(const e of game.enemies){let d=dist(o,e);if(d<bd){bd=d;best=e}}return best}
function update(dt){if(!game.running)return;game.t+=dt;let p=game.player;let dx=(keys.KeyD?1:0)-(keys.KeyA?1:0),dy=(keys.KeyS?1:0)-(keys.KeyW?1:0),len=Math.hypot(dx,dy)||1;p.x=clamp(p.x+dx/len*p.speed*dt,35,W-35);p.y=clamp(p.y+dy/len*p.speed*dt,45,H-45);p.shot-=dt;p.pulse-=dt;if(mouse.down&&p.shot<=0){shoot(p,mouse);p.shot=.13}if(keys.Space&&p.pulse<=0){p.pulse=6;game.flash=.35;for(const e of game.enemies)if(dist(p,e)<210){e.hp-=45;e.x+=(e.x-p.x)*.2;e.y+=(e.y-p.y)*.2}burst(p.x,p.y,'#67f9ff',30)}
  game.spawn-=dt;if(game.spawn<=0){spawn(false);game.spawn=Math.max(.3,1.3-game.wave*.07)}game.nextWave-=dt;if(game.nextWave<=0){game.wave++;game.nextWave=18;if(game.wave%3===0)spawn(true);p.hp=Math.min(p.max,p.hp+18);updateUI()}
  for(const a of game.allies){a.shot-=dt;let e=nearest(a);if(e&&a.shot<=0){shoot(a,e);a.shot=a.type==='mech'?.38:.55}}
  for(const t of game.turrets){t.shot-=dt;let e=nearest(t);if(e&&t.shot<=0&&dist(t,e)<430){shoot(t,e);t.shot=.75}}
  for(const e of game.enemies){let target=p,dd=dist(e,p);for(const a of game.allies)if(dist(e,a)<dd){target=a;dd=dist(e,a)}let ex=target.x-e.x,ey=target.y-e.y,l=Math.hypot(ex,ey)||1;e.x+=ex/l*e.speed*dt;e.y+=ey/l*e.speed*dt;e.hit-=dt;e.attack-=dt;if(dd<e.r+target.r&&e.attack<=0){target.hp-=e.boss?18:8;e.attack=.7;game.shake=8;burst(target.x,target.y,'#ff4165',7)}}
  for(const b of game.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.ally){for(const e of game.enemies)if(e.hp>0&&dist(b,e)<e.r+b.r){e.hp-=b.damage;b.life=0;e.hit=.08;burst(b.x,b.y,'#45eeff',5);break}}}
  for(const e of game.enemies)if(e.hp<=0){game.score+=e.boss?1000:100;game.coins+=e.boss?10:1;game.kills++;burst(e.x,e.y,e.type.includes('Slime')?'#7cff28':e.type.includes('Rock')?'#c22cff':'#ff4b21',18);if(Math.random()<.22)game.drops.push({x:e.x,y:e.y,r:14,life:8})}
  game.enemies=game.enemies.filter(e=>e.hp>0&&e.y<H+100);game.bullets=game.bullets.filter(b=>b.life>0&&b.x>-40&&b.x<W+40&&b.y>-40&&b.y<H+40);for(const d of game.drops){d.life-=dt;if(dist(d,p)<p.r+d.r){d.life=0;game.coins+=5;p.hp=Math.min(p.max,p.hp+6)}}game.drops=game.drops.filter(d=>d.life>0);for(const q of game.particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.95;q.vy*=.95;q.life-=dt}game.particles=game.particles.filter(q=>q.life>0);game.allies=game.allies.filter(a=>a.hp>0);game.flash-=dt;game.shake*=.86;if(p.hp<=0)end();updateUI()}
function updateUI(){if(!game)return;ui.wave.textContent=`ONDATA ${game.wave}`;ui.score.textContent=game.score.toLocaleString('it-IT');ui.coins.textContent=`★ ${game.coins}`;ui.hp.style.width=`${Math.max(0,game.player.hp)}%`;let b=game.enemies.find(e=>e.boss);ui.boss.classList.toggle('hidden',!b);if(b)ui.bossBar.style.width=`${b.hp/b.max*100}%`}
function background(){ctx.fillStyle='#030a15';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#0c3c5744';ctx.lineWidth=1;let s=70,ox=(game?.t*12||0)%s;for(let x=-s+ox;x<W;x+=s){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-180,H);ctx.stroke()}for(let y=0;y<H;y+=s){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}let g=ctx.createRadialGradient(W/2,H*.75,10,W/2,H*.75,W*.65);g.addColorStop(0,'#07507a44');g.addColorStop(1,'#0000');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function draw(){background();if(!game)return;ctx.save();ctx.translate(rnd(-game.shake,game.shake),rnd(-game.shake,game.shake));sprite({x:W/2,y:H-62,r:44},img.reactor,105);sprite({x:W/2,y:H-38,r:46},img.portal,120);sprite({x:W/2,y:H-30,r:40},img.barrier,110);for(const t of game.turrets){let e=nearest(t),a=e?Math.atan2(e.y-t.y,e.x-t.x):0;sprite(t,img.turret,92,a)}for(const d of game.drops)sprite(d,img.coin,34);for(const a of game.allies){let e=nearest(a),ang=e?Math.atan2(e.y-a.y,e.x-a.x):0;sprite(a,img[a.type],a.type==='mech'?72:62,ang*.06);health(a)}for(const e of game.enemies){sprite(e,img[e.type],e.r*2.75);if(e.hit>0){ctx.globalCompositeOperation='source-atop';ctx.fillStyle='#fff8';ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,7);ctx.fill();ctx.globalCompositeOperation='source-over'}if(e.boss)health(e)}for(const b of game.bullets){ctx.fillStyle=b.ally?'#69f7ff':'#ff3b56';ctx.shadowBlur=14;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill();ctx.shadowBlur=0}let p=game.player,a=Math.atan2(mouse.y-p.y,mouse.x-p.x),weapon=img[['gun1','gun2','gun3'][(game.wave-1)%3]];sprite(p,img.player,76,a/10);sprite({x:p.x+Math.cos(a)*25,y:p.y+Math.sin(a)*25,r:15},weapon,50,a);for(const q of game.particles){ctx.globalAlpha=q.life/q.max;ctx.fillStyle=q.color;ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,7);ctx.fill()}ctx.globalAlpha=1;if(p.pulse>5.6){ctx.strokeStyle='#59f7ff';ctx.lineWidth=8;ctx.globalAlpha=(p.pulse-5.6)*2.5;ctx.beginPath();ctx.arc(p.x,p.y,(6-p.pulse)*520,0,7);ctx.stroke()}ctx.restore();if(game.flash>0){ctx.fillStyle=`rgba(80,240,255,${game.flash*.2})`;ctx.fillRect(0,0,W,H)}}
function health(o){ctx.fillStyle='#170d1a';ctx.fillRect(o.x-o.r,o.y-o.r-11,o.r*2,5);ctx.fillStyle=o.boss?'#ff315b':'#36f27d';ctx.fillRect(o.x-o.r,o.y-o.r-11,o.r*2*Math.max(0,o.hp/o.max),5)}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(game)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function start(){document.querySelector('#start').classList.add('hidden');document.querySelector('#end').classList.add('hidden');reset()}function end(){game.running=false;document.querySelector('#result').textContent=`Hai resistito fino all'ondata ${game.wave}, eliminando ${game.kills} mostri e totalizzando ${game.score.toLocaleString('it-IT')} punti.`;document.querySelector('#end').classList.remove('hidden')}document.querySelector('#play').onclick=start;document.querySelector('#again').onclick=start;
