const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
const ui={level:$('#wave'),crowd:$('#score'),lives:$('#lives'),timer:$('#timer'),coins:$('#coins'),progress:$('#hp'),boss:$('#boss'),bossBar:$('#boss i')};
const assetNames=['player','soldierRed','ally','mech','tank','gun1','gun2','gun3','monsterSlime','monsterSlimeBig','monsterRock','monsterRockBig','monsterEye','monsterEyeBig','monsterClaw','monsterClawBig','turret','portal','barrier','reactor','coin'],images={};assetNames.forEach(n=>{images[n]=new Image();images[n].src=`assets/${n}.png`});function cleanGeneratedBackground(im){const c=document.createElement('canvas'),x=c.getContext('2d');c.width=im.naturalWidth;c.height=im.naturalHeight;x.drawImage(im,0,0);const data=x.getImageData(0,0,c.width,c.height),p=data.data;for(let i=0;i<p.length;i+=4){const hi=Math.max(p[i],p[i+1],p[i+2]),lo=Math.min(p[i],p[i+1],p[i+2]);if(lo>226&&hi-lo<13)p[i+3]=0}x.putImageData(data,0,0);im.onload=null;im.src=c.toDataURL('image/png')}images.metalGate=new Image();images.metalGate.onload=()=>cleanGeneratedBackground(images.metalGate);images.metalGate.src='assets/metal-gate.png';images.defenseWall=new Image();images.defenseWall.onload=()=>cleanGeneratedBackground(images.defenseWall);images.defenseWall.src='assets/defense-wall.png';
let W=0,H=0,D=1,last=0,state=null,difficulty='normal',language='it',audio=null,musicMuted=false,pointer={x:0,down:false};
const modes={easy:{enemy:1,boss:1,speed:.9,rate:1,label:'FACILE'},normal:{enemy:1.55,boss:1.8,speed:1.25,rate:.88,label:'NORMALE'},hard:{enemy:2.25,boss:2.8,speed:1.65,rate:.74,label:'DIFFICILE'}};
const words={it:{intro:'Resisti almeno 60 secondi, supera i portali e abbatti le casse numerate per ottenere armi ed evoluzioni.',language:'LINGUA',difficulty:'DIFFICOLTÀ',easy:'FACILE',normal:'NORMALE',hard:'DIFFICILE',play:'INIZIA BATTAGLIA',paused:'PAUSA',resume:'RIPRENDI',restart:'RICOMINCIA',home:'TORNA ALLA HOME'},en:{intro:'Survive for at least 60 seconds, cross the gates and destroy numbered crates to unlock weapons and upgrades.',language:'LANGUAGE',difficulty:'DIFFICULTY',easy:'EASY',normal:'NORMAL',hard:'HARD',play:'START BATTLE',paused:'PAUSED',resume:'RESUME',restart:'RESTART',home:'BACK TO HOME'},es:{intro:'Resiste al menos 60 segundos, atraviesa los portales y destruye cajas numeradas para conseguir armas y mejoras.',language:'IDIOMA',difficulty:'DIFICULTAD',easy:'FÁCIL',normal:'NORMAL',hard:'DIFÍCIL',play:'INICIAR BATALLA',paused:'PAUSA',resume:'CONTINUAR',restart:'REINICIAR',home:'VOLVER AL INICIO'}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a);
function applyLanguage(){document.documentElement.lang=language;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=words[language][el.dataset.i18n]||el.textContent)}

/*function ensureAudio()
{if(audio)return;const AC=window.AudioContext||window.webkitAudioContext;
    if(!AC)return;const context=new AC(),gain=context.createGain(),bass=context.createOscillator(),lead=context.createOscillator(),lfo=context.createOscillator(),
    lfoGain=context.createGain();bass.type='triangle';bass.frequency.value=82;lead.type='sine';lead.frequency.value=164;lfo.frequency.value=.22;lfoGain.gain.value=22;lfo.connect(lfoGain);
    lfoGain.connect(lead.frequency);bass.connect(gain);lead.connect(gain);gain.connect(context.destination);gain.gain.value=.055;bass.start();lead.start();lfo.start();audio={context,gain}}*/

    function ensureAudio() {
  if (audio) return;
  
  // Crea l'elemento audio con il tuo file
  const musicFile = new Audio('assets/kulakovka-break-291455.mp3'); 
  musicFile.loop = true; // Riproduce in ciclo continuo
  musicFile.volume = 0.5; // Volume da 0.0 a 1.0

  audio = { 
    element: musicFile, 
    playing: false 
  };
}

/*function toggleMusic(){ensureAudio();musicMuted=!musicMuted;if(audio)audio.gain.gain.setTargetAtTime(musicMuted?0:.055,audio.context.currentTime,.08);$('#music').textContent=musicMuted?'🔇':'🔊'}*/

function toggleMusic() {
  ensureAudio();
  musicMuted = !musicMuted;

  if (musicMuted) {
    audio.element.pause();
  } else {
    audio.element.play();
  }

  $('#music').textContent = musicMuted ? '🔇' : '🔊';
}

function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*D;canvas.height=H*D;ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
function point(e){const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)*W/r.width}canvas.onpointerdown=e=>{pointer.down=true;point(e);canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=point;canvas.onpointerup=canvas.onpointercancel=()=>pointer.down=false;
addEventListener('keydown',e=>{if(!state)return;if(['ArrowLeft','KeyA'].includes(e.code))pointer.x=state.cannon.x-80;if(['ArrowRight','KeyD'].includes(e.code))pointer.x=state.cannon.x+80});
function reset(level=1){const w=Math.min(W*.86,620),left=(W-w)/2,m=modes[difficulty],dividerX=left+w*[.36,.62,.48,.7,.3][(level-1)%5],dividerY=H*[.44,.56,.38,.51,.61][(level-1)%5];state={running:true,paused:false,won:false,level,difficulty,coins:0,time:0,minDuration:60,reinforce:7,nextEvent:3,eventIndex:0,crateIndex:0,lives:20,power:0,powerReady:false,road:{left,right:left+w,w},cannon:{x:W/2,y:H-72,cool:0,rate:.105/m.rate,damage:1,weapon:0,evolution:0},units:[],enemies:[],particles:[],texts:[],gates:[],crates:[],hazards:[],decorations:[],divider:{x:dividerX,y:dividerY,w:46,h:[115,155,135,180,125][(level-1)%5]},spawned:0,maxSpawn:9999,boss:null,progress:0,scroll:0,phase:'deploy'};pointer.x=W/2;makeDecorations();makeHazards();makeArmy();updateUI()}
function makeDecorations(){const decor=['player','soldierRed','ally','mech','tank','turret','portal','barrier','reactor','coin','monsterSlime','monsterRock','monsterEye','monsterClaw'];state.decorations=decor.map((type,i)=>({type,x:i%2?state.road.right+45:state.road.left-45,y:(i%7)*115-80,side:i%2?1:-1,size:type==='coin'?38:58}))}
function makeHazards(){const r=state.road,level=state.level,types=level===1?['block']:level===2?['door','block']:level===3?['spinner','door']:level===4?['pipe','spinner','block']:['block','door','spinner','pipe'];state.hazards=types.map((type,i)=>({id:`h${i}`,type,x:type==='door'?r.left+r.w*(i%2?.68:.32):(i%2?r.left+r.w*.7:r.left+r.w*.3),y:H*(.25+i*.14),w:type==='door'?Math.min(r.w*.32,210):92,h:type==='door'?46:64,hp:30+level*12+i*10,max:30+level*12+i*10,phase:i*1.7,angle:0,open:false}))}
function spawnGates(){const r=state.road,gap=34,gw=Math.min(150,(r.w-gap*3)/2),basic=[[{kind:'add',value:10},{kind:'sub',value:-5}],[{kind:'sub',value:-20},{kind:'add',value:28+state.level*2}],[{kind:'add',value:18},{kind:'sub',value:-10}],[{kind:'sub',value:-15},{kind:'mul',value:2}],[{kind:'add',value:35},{kind:'sub',value:-20}]],advanced=[[{kind:'mul',value:2},{kind:'sub',value:-20}],[{kind:'add',value:25},{kind:'mul',value:2}],[{kind:'sub',value:-15},{kind:'mul',value:3}],[{kind:'mul',value:2},{kind:'add',value:40}]],sets=state.level>=4?advanced:basic,pair=sets[state.eventIndex%sets.length],group=`g${state.eventIndex}`,total=gw*2+gap,offset=rnd(-Math.max(0,(r.w-total)/2-14),Math.max(0,(r.w-total)/2-14)),start=W/2-total/2+offset;pair.forEach((g,i)=>state.gates.push({...g,id:`${group}-${i}`,group,x:start+i*(gw+gap),y:-58-rnd(0,28),w:gw,h:38,used:false,speed:58+state.level*2+rnd(-3,4)}));state.eventIndex++}
function spawnCrate(){const r=state.road,rewards=[{name:'BLASTER LV.2',kind:'weapon',icon:1},{name:'EVOLUZIONE',kind:'evolution',icon:2},{name:'RAFFICA',kind:'weapon',icon:2}],reward=rewards[state.crateIndex%rewards.length],hp=38+state.level*8+state.eventIndex*3;state.crates.push({id:`c${state.eventIndex}`,x:r.left+r.w*(state.eventIndex%2?.7:.3),y:-72,w:66,h:54,hp,max:hp,reward,dead:false,hit:0,speed:48+state.level*2});state.crateIndex++;state.eventIndex++}
function spawnEvent(){if(state.level>=4){if(state.eventIndex%5===4)spawnCrate();else spawnGates();state.nextEvent+=4.5}else{if(state.eventIndex%3===2)spawnCrate();else spawnGates();state.nextEvent+=8}}
function makeArmy(){const m=modes[difficulty],ease=state.level>=2?.95:1,count=Math.round((42+state.level*12)*m.enemy*ease*1.15);for(let i=0;i<count;i++){const row=Math.floor(i/10),col=i%10,giant=i>0&&i%35===0;state.enemies.push({x:W/2+(col-4.5)*13+rnd(-3,3),y:145-row*12+rnd(-3,3),r:giant?13:5.3,phase:rnd(0,6.28),speed:rnd(21,36)*m.speed*ease*.9*(giant?.65:1),giant,hp:giant?(10+state.level*2)*ease:1})}const types=['monsterClawBig','monsterRockBig','monsterEyeBig','monsterSlimeBig'],growth=Math.pow(1.22,state.level-1),hp=Math.round((95+state.level*34)*m.boss*growth*ease),total=1+Math.floor((state.level-1)/2);state.boss={x:W/2,y:-65,r:34,hp,max:hp,type:types[(state.level-1)%4],hit:0,speed:(34+state.level*3)*m.speed*ease,phase:0,active:false,remaining:total,total,index:1}}
function reinforce(){const m=modes[difficulty],ease=state.level>=2?.95:1,count=Math.round((14+state.level*4)*m.enemy*ease*1.15);for(let i=0;i<count;i++){const giant=i===0&&Math.random()<.7;state.enemies.push({x:W/2+rnd(-85,85),y:rnd(82,120),r:giant?14:5.3,phase:rnd(0,6.28),speed:rnd(27,45)*m.speed*ease*.9*(giant?.6:1),giant,hp:giant?(12+state.level*3)*ease:1})}text(W/2,150,'RINFORZI NEMICI!','#ff4055');burst(W/2,125,'#ff3048',18)}
function nextBoss(){const b=state.boss,types=['monsterClawBig','monsterRockBig','monsterEyeBig','monsterSlimeBig'];b.remaining--;b.index++;b.type=types[(state.level+b.index-2)%4];b.hp=b.max=Math.round(b.max*1.18);b.x=W/2;b.y=-65;b.hit=0;b.active=true;text(W/2,125,`BOSS ${b.index}/${b.total}`,'#ffdf35');burst(W/2,70,'#ffad20',35)}
function addUnit(x,y,giant=false){if(state.units.length<650)state.units.push({x:x+rnd(-3,3),y:y+rnd(-2,2),r:giant?13:5.2,vx:rnd(-12,12),passed:{},crates:{},hazards:{},phase:rnd(0,6.28),giant,hp:giant?18:1})}
function launchGiant(){if(!state?.running||state.paused||!state.powerReady)return;state.power=0;state.powerReady=false;addUnit(state.cannon.x,state.cannon.y-45,true);text(state.cannon.x,state.cannon.y-95,'GIGANTE!','#fff12f');burst(state.cannon.x,state.cannon.y-45,'#ffe62e',35)}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)state.particles.push({x,y,vx:rnd(-110,110),vy:rnd(-120,60),life:rnd(.3,.8),max:.8,color,r:rnd(2,5)})}
function text(x,y,value,color='#fff'){state.texts.push({x,y,value,color,life:1,max:1})}
function reward(box){const c=state.cannon;c.evolution++;c.weapon=Math.max(c.weapon,box.reward.icon);if(box.reward.kind==='weapon')c.rate*=.68;else{c.damage*=2;c.rate*=.82}state.coins+=20;text(box.x,box.y-32,`${box.reward.name} SBLOCCATO!`,'#fff34d');burst(box.x,box.y,'#ffcc32',35)}
function useGate(g,entrants){if(g.used||!entrants.length)return;state.gates.filter(x=>x.group===g.group).forEach(x=>x.used=true);const originals=[...state.units],before=originals.length;if(g.kind==='sub'){const loss=Math.min(Math.abs(g.value),Math.max(0,before-1)),victims=[...originals].sort((a,b)=>Math.hypot(a.x-(g.x+g.w/2),a.y-g.y)-Math.hypot(b.x-(g.x+g.w/2),b.y-g.y)).slice(0,loss);state.units=state.units.filter(u=>!victims.includes(u));text(g.x+g.w/2,g.y-12,`${before} → ${state.units.length}`,'#ff4055');burst(g.x+g.w/2,g.y+g.h/2,'#ff4055',18);return}const target=g.kind==='mul'?Math.min(before*g.value,650):Math.min(before+g.value,650),amount=target-before;for(let i=0;i<amount;i++){const u=originals[i%originals.length];addUnit(u.x+rnd(-18,18),u.y+rnd(4,28))}text(g.x+g.w/2,g.y-12,`${before} → ${state.units.length}`,'#ffef46');burst(g.x+g.w/2,g.y+g.h/2,'#55ecff',24)}
function updateHazards(dt){for(const h of state.hazards){h.angle+=dt*4;h.open=Math.sin(state.time*1.8+h.phase)>0;const spinHit=o=>{const dx=o.x-h.x,dy=o.y-h.y,along=dx*Math.cos(h.angle)+dy*Math.sin(h.angle),across=-dx*Math.sin(h.angle)+dy*Math.cos(h.angle);if(Math.abs(along)<72+o.r&&Math.abs(across)<9+o.r){const force=190*(1-Math.min(1,Math.abs(along)/82));o.x+=Math.cos(h.angle+Math.PI/2)*force*dt;o.y+=Math.sin(h.angle+Math.PI/2)*force*dt;return true}return false};if(h.type==='block'&&h.hp<=0)continue;for(const u of state.units){if(h.type==='spinner'){if(spinHit(u)){u.vx+=Math.cos(h.angle+Math.PI/2)*150;burst(u.x,u.y,'#ffe14d',2)}continue}const near=Math.abs(u.x-h.x)<h.w/2+u.r&&Math.abs(u.y-h.y)<h.h/2+u.r;if(!near)continue;if(h.type==='block'&&!u.hazards[h.id]){u.hazards[h.id]=true;h.hp-=u.giant?8:1;u.y+=u.giant?4:18;burst(u.x,u.y,'#ffcf32',2)}else if(h.type==='door'&&!h.open)u.y+=12;else if(h.type==='pipe')u.vx+=(u.x<h.x?-1:1)*55}for(const e of state.enemies){if(h.type==='spinner'){if(spinHit(e))e.x+=Math.cos(h.angle+Math.PI/2)*75*dt;continue}const near=Math.abs(e.x-h.x)<h.w/2+e.r&&Math.abs(e.y-h.y)<h.h/2+e.r;if(!near)continue;if(h.type==='block'){e.y-=10;h.hp-=e.giant?2:.3}else if(h.type==='door'&&!h.open)e.y-=11;else if(h.type==='pipe')e.x+=(e.x<h.x?-1:1)*35*dt}}}
function update(dt){if(!state?.running||state.paused)return;state.time+=dt;state.scroll=(state.scroll+190*dt)%70;const r=state.road,c=state.cannon,b=state.boss;if(state.time>=state.minDuration&&!b.active){b.active=true;text(W/2,125,'IL BOSS È ARRIVATO!','#ffcf28');burst(W/2,70,'#ff6b20',45)}c.x+=(clamp(pointer.x,r.left+34,r.right-34)-c.x)*Math.min(1,dt*(pointer.down?14:6));c.cool-=dt;if(state.spawned<state.maxSpawn&&c.cool<=0){addUnit(c.x,c.y-34);state.spawned++;c.cool=c.rate}if(state.time>=state.reinforce&&state.time<state.minDuration){reinforce();state.reinforce+=7}if(state.time>=state.nextEvent&&state.time<57)spawnEvent();for(const g of state.gates)g.y+=g.speed*dt;for(const box of state.crates)box.y+=box.speed*dt;state.gates=state.gates.filter(g=>g.y<H+70);state.crates=state.crates.filter(box=>box.y<H+80&&!box.dead)
 const speed=state.phase==='deploy'?145:190,d=state.divider;for(const u of state.units){u.y-=speed*dt;if(!b.active&&u.y<H*.27)u.y=H*.27+rnd(0,14);u.x+=clamp((W/2-u.x)*.14+u.vx,-78,78)*dt;if(Math.abs(u.x-d.x)<d.w/2+7&&Math.abs(u.y-d.y)<d.h/2+8){const side=u.x<d.x?-1:1;u.x=d.x+side*(d.w/2+9);u.vx=side*rnd(28,55)}u.vx*=.98;u.x=clamp(u.x,r.left+10,r.right-10)}
 for(const g of state.gates){const hit=state.units.filter(u=>!u.passed[g.id]&&u.y<g.y+g.h&&u.y>g.y-10&&u.x>=g.x&&u.x<=g.x+g.w);hit.forEach(u=>u.passed[g.id]=true);useGate(g,hit)}
 for(const box of state.crates){if(box.dead)continue;box.hit-=dt;for(const u of state.units){if(u.crates[box.id]||Math.abs(u.x-box.x)>box.w*.58||Math.abs(u.y-box.y)>box.h*.58)continue;u.crates[box.id]=true;box.hp-=c.damage;box.hit=.12;u.y+=18;u.vx+=rnd(-25,25);burst(u.x,u.y,'#ffd34d',2)}if(box.hp<=0){box.dead=true;reward(box)}}
 updateHazards(dt);state.power=Math.min(10,state.power+dt);state.powerReady=state.power>=10;const power=$('#power');power.style.left=`${clamp(c.x+48,8,W-62)}px`;power.style.top=`${c.y-20}px`;$('#power em').style.height=`${state.power*10}%`;power.classList.toggle('ready',state.powerReady);
 for(const e of state.enemies){e.y+=e.speed*dt;e.x+=Math.sin(state.time*8+e.phase)*10*dt;if(Math.abs(e.x-d.x)<d.w/2+e.r&&Math.abs(e.y-d.y)<d.h/2+e.r){const side=e.x<d.x?-1:1;e.x=d.x+side*(d.w/2+e.r+2);e.phase+=1.2}e.x=clamp(e.x,r.left+8,r.right-8)}const breached=state.enemies.filter(e=>e.y>state.cannon.y-45);if(breached.length){state.lives=Math.max(0,state.lives-breached.length);state.enemies=state.enemies.filter(e=>e.y<=state.cannon.y-45);burst(state.cannon.x,state.cannon.y-35,'#ff3048',breached.length*3)}if(b.active){b.y+=b.speed*dt;b.x=W/2+Math.sin(state.time*1.7)*Math.min(55,state.road.w*.11)}b.phase+=dt;b.hit-=dt;
 const deadU=new Set(),deadE=new Set();for(let i=0;i<state.units.length;i++){const u=state.units[i];let best=-1,bd=u.giant?25:15;for(let j=0;j<state.enemies.length;j++){if(deadE.has(j))continue;const e=state.enemies[j],d=Math.hypot(u.x-e.x,u.y-e.y);if(d<bd){bd=d;best=j}}if(best>=0){const e=state.enemies[best];e.hp-=u.giant?5:1;u.hp-=e.giant?5:1;if(u.hp<=0)deadU.add(i);if(e.hp<=0)deadE.add(best);burst(u.x,u.y,u.giant?'#ffe62e':'#fff',u.giant?8:3)}}state.units=state.units.filter((_,i)=>!deadU.has(i));state.enemies=state.enemies.filter((_,i)=>!deadE.has(i));
 let hitters=0,bossDamage=0;state.units=state.units.filter(u=>{if(b.active&&Math.hypot(u.x-b.x,u.y-b.y)<b.r+10){hitters++;bossDamage+=(u.giant?30:3)*c.damage;return false}return u.y>-20});if(hitters){b.hp-=bossDamage;b.hit=.12;burst(b.x,b.y+15,'#57dfff',hitters*2);text(b.x,b.y+54,`-${bossDamage}`)}
 if(b.active&&b.hp<=0){if(b.remaining>1)nextBoss();else{state.running=false;state.won=true;state.coins+=50+state.level*10;burst(b.x,b.y,'#ffd93d',60);setTimeout(victorySequence,500)}}else if(state.time>=state.minDuration&&(state.lives<=0||b.active&&b.y>state.cannon.y-90)){state.running=false;setTimeout(()=>finish(false),350)}
 for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=140*dt;p.life-=dt}state.particles=state.particles.filter(p=>p.life>0);for(const t of state.texts){t.y-=28*dt;t.life-=dt}state.texts=state.texts.filter(t=>t.life>0);state.progress=clamp(1-(state.enemies.length+b.hp/3)/(43+state.level*9),0,1);updateUI()}
function updateUI(){if(!state)return;const remain=Math.max(0,Math.ceil(state.minDuration-state.time)),b=state.boss;ui.level.textContent=`LIVELLO ${state.level} · ${modes[state.difficulty].label}`;ui.crowd.textContent=`FOLLA ${state.units.length}`;ui.lives.textContent=`❤️ ${state.lives}`;ui.timer.textContent=`00:${String(remain).padStart(2,'0')}`;ui.timer.style.color=remain<=10?'#ff4055':'#fff';ui.coins.textContent=`★ ${state.coins}`;ui.progress.style.width=`${Math.min(1,state.time/state.minDuration)*100}%`;ui.boss.classList.toggle('hidden',!b.active);if(b.active){$('#boss b').textContent=`BOSS ${b.index}/${b.total}`;ui.bossBar.style.width=`${Math.max(0,b.hp/b.max*100)}%`}}
function road(){const r=state?.road||{left:W*.15,right:W*.85};const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#61caff');sky.addColorStop(.48,'#d9f5ff');sky.addColorStop(.49,'#79c9ed');sky.addColorStop(1,'#3680ba');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#edf2f5';ctx.beginPath();ctx.moveTo(r.left+45,0);ctx.lineTo(r.right-45,0);ctx.lineTo(r.right,H);ctx.lineTo(r.left,H);ctx.closePath();ctx.fill();ctx.strokeStyle='#c5cfd6';ctx.lineWidth=3;for(let y=-70+(state?.scroll||0);y<H;y+=70){ctx.beginPath();ctx.moveTo(r.left+(H-y)*.055,y);ctx.lineTo(r.right-(H-y)*.055,y);ctx.stroke()}ctx.fillStyle='#46515d';ctx.beginPath();ctx.moveTo(r.left+35,0);ctx.lineTo(r.left,H);ctx.lineTo(r.left-24,H);ctx.lineTo(r.left+20,0);ctx.fill();ctx.beginPath();ctx.moveTo(r.right-35,0);ctx.lineTo(r.right,H);ctx.lineTo(r.right+24,H);ctx.lineTo(r.right-20,0);ctx.fill()}
function unit(u,red=false){const s=(.72+u.y/H*.45)*(u.giant?2.05:1),walk=Math.sin(state.time*(u.giant?8:13)+u.phase)*3,light=red?(u.giant?'#ffb13b':'#ff6670'):(u.giant?'#fffbd0':'#67d8ff'),dark=red?'#790817':u.giant?'#c47a00':'#004caa',base=red?'#ee1730':u.giant?'#ffd000':'#078dff';ctx.save();ctx.translate(u.x,u.y);ctx.scale(s,s);ctx.fillStyle='#08233a55';ctx.beginPath();ctx.ellipse(0,8,7,3,0,0,7);ctx.fill();ctx.strokeStyle=dark;ctx.lineWidth=2.2;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-2,3);ctx.lineTo(-3-walk*.35,10);ctx.moveTo(2,3);ctx.lineTo(3+walk*.35,10);ctx.moveTo(-3,-1);ctx.lineTo(-7-walk*.45,4);ctx.moveTo(3,-1);ctx.lineTo(7+walk*.45,4);ctx.stroke();const body=ctx.createLinearGradient(-4,-4,5,6);body.addColorStop(0,light);body.addColorStop(.42,base);body.addColorStop(1,dark);ctx.fillStyle=body;ctx.beginPath();ctx.roundRect(-4,-3,8,10,3);ctx.fill();ctx.stroke();const head=ctx.createRadialGradient(-2,-8,1,0,-6,6);head.addColorStop(0,'#fff');head.addColorStop(.2,light);head.addColorStop(.7,base);head.addColorStop(1,dark);ctx.fillStyle=head;ctx.beginPath();ctx.arc(0,-7,5,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#fff9';ctx.beginPath();ctx.arc(-1.5,-8.5,1.2,0,7);ctx.fill();ctx.restore()}
function round(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function gate(g){ctx.save();ctx.globalAlpha=g.used?.3:1;ctx.shadowBlur=18;ctx.shadowColor=g.kind==='sub'?'#ff2748':'#00bfff';const grad=ctx.createLinearGradient(0,g.y,0,g.y+g.h);grad.addColorStop(0,g.kind==='sub'?'#ff6377':'#2be9ff');grad.addColorStop(1,g.kind==='sub'?'#d5092c':'#0879ff');ctx.fillStyle=grad;round(g.x,g.y,g.w,g.h,10);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font=`900 ${Math.min(34,g.w*.25)}px Rajdhani`;ctx.textAlign='center';ctx.textBaseline='middle';const label=g.kind==='mul'?`×${g.value}`:g.kind==='sub'?`${g.value}`:`+${g.value}`;ctx.fillText(label,g.x+g.w/2,g.y+g.h/2);ctx.restore()}
function crate(box){if(box.dead)return;ctx.save();ctx.translate(box.x,box.y);const front=ctx.createLinearGradient(0,-box.h/2,0,box.h/2);front.addColorStop(0,box.hit>0?'#fff':'#ffbe39');front.addColorStop(.45,'#c9700c');front.addColorStop(1,'#713500');ctx.fillStyle=front;round(-box.w/2,-box.h/2,box.w,box.h,7);ctx.fill();ctx.strokeStyle='#4a2608';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#ffd767';ctx.beginPath();ctx.moveTo(-box.w/2,-box.h/2);ctx.lineTo(-box.w/2+10,-box.h/2-9);ctx.lineTo(box.w/2+8,-box.h/2-9);ctx.lineTo(box.w/2,-box.h/2);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#713500';ctx.beginPath();ctx.moveTo(box.w/2,box.h/2);ctx.lineTo(box.w/2+8,box.h/2-9);ctx.lineTo(box.w/2+8,-box.h/2-9);ctx.lineTo(box.w/2,-box.h/2);ctx.closePath();ctx.fill();ctx.fillStyle='#ffdc43';ctx.fillRect(-box.w/2+5,-6,box.w-10,12);ctx.strokeStyle='#fff5a8';ctx.lineWidth=2;ctx.strokeRect(-box.w/2+5,-6,box.w-10,12);ctx.fillStyle='#4b2604';ctx.font='900 21px Rajdhani';ctx.textAlign='center';ctx.fillText(Math.max(0,Math.ceil(box.hp)),0,7);ctx.fillStyle='#fff';ctx.font='900 11px Rajdhani';ctx.fillText(box.reward.name,0,-box.h/2-39);const prize=images[['gun1','gun2','gun3'][box.reward.icon]];if(prize?.complete){ctx.shadowBlur=12;ctx.shadowColor='#fff34d';ctx.drawImage(prize,-23,-box.h/2-34,46,46)}ctx.restore()}
function hazard(h){if(h.type==='block'&&h.hp<=0)return;ctx.save();ctx.translate(h.x,h.y);ctx.lineWidth=4;ctx.textAlign='center';ctx.textBaseline='middle';if(h.type==='block'){ctx.fillStyle='#17212c66';ctx.beginPath();ctx.ellipse(5,h.h/2+8,h.w*.65,10,0,0,7);ctx.fill();const stone=ctx.createLinearGradient(0,-h.h/2,0,h.h/2);stone.addColorStop(0,'#aebdca');stone.addColorStop(.45,'#526474');stone.addColorStop(1,'#263542');ctx.fillStyle=stone;round(-h.w/2,-h.h/2,h.w,h.h,5);ctx.fill();ctx.strokeStyle='#182733';ctx.stroke();ctx.strokeStyle='#263846';ctx.lineWidth=2;for(let y=-h.h/2+18;y<h.h/2;y+=18){ctx.beginPath();ctx.moveTo(-h.w/2,y);ctx.lineTo(h.w/2,y);ctx.stroke();for(let x=-h.w/2+((y/18)%2?18:0);x<h.w/2;x+=35){ctx.beginPath();ctx.moveTo(x,y-18);ctx.lineTo(x,y);ctx.stroke()}}ctx.fillStyle='#172330dd';round(-25,-11,50,22,5);ctx.fill();ctx.strokeStyle='#ffbd24';ctx.stroke();ctx.fillStyle='#fff';ctx.font='900 18px Rajdhani';ctx.fillText(Math.max(0,Math.ceil(h.hp)),0,1)}else if(h.type==='door'){const gap=h.open?h.w*.64:8,panel=(h.w-gap)/2,metal=ctx.createLinearGradient(0,-17,0,17);metal.addColorStop(0,'#eef8ff');metal.addColorStop(.22,'#7790a3');metal.addColorStop(.55,'#1a2a38');metal.addColorStop(1,'#607b91');ctx.fillStyle='#172736';round(-h.w/2-9,-22,18,44,5);ctx.fill();round(h.w/2-9,-22,18,44,5);ctx.fill();ctx.fillStyle=metal;ctx.strokeStyle=h.open?'#41ff9a':'#ffb51d';ctx.shadowBlur=10;ctx.shadowColor=ctx.strokeStyle;round(-h.w/2,-15,panel,30,4);ctx.fill();ctx.stroke();round(gap/2,-15,panel,30,4);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#0b1723';for(let x=-h.w/2+14;x<h.w/2;x+=24)ctx.fillRect(x,-11,6,22);ctx.fillStyle='#31dcff';ctx.fillRect(-h.w/2-5,-14,9,10);ctx.fillRect(h.w/2-4,-14,9,10);ctx.fillStyle=h.open?'#57ff94':'#ff4055';ctx.font='900 12px Rajdhani';ctx.fillText(h.open?'PORTA APERTA':'PORTA CHIUSA',0,-28)}else if(h.type==='spinner'){ctx.rotate(h.angle);const beam=ctx.createLinearGradient(0,-8,0,8);beam.addColorStop(0,'#fff18a');beam.addColorStop(.45,'#ffb400');beam.addColorStop(1,'#9a4c00');ctx.fillStyle=beam;round(-72,-8,144,16,7);ctx.fill();ctx.strokeStyle='#27364a';ctx.stroke();ctx.fillStyle='#ed2939';ctx.fillRect(-56,-7,14,14);ctx.fillRect(42,-7,14,14);ctx.fillStyle='#169cff';ctx.beginPath();ctx.arc(0,0,18,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#e9f8ff';ctx.beginPath();ctx.arc(-4,-5,5,0,7);ctx.fill()}else{ctx.strokeStyle='#24dfff';ctx.lineWidth=10;ctx.beginPath();ctx.arc(0,0,31,0,7);ctx.stroke();ctx.strokeStyle='#25405c';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,20,0,7);ctx.stroke();ctx.fillStyle='#fff';ctx.font='900 13px Rajdhani';ctx.fillText('TUBO',0,1)}ctx.restore()}
function assetHazard(h){if(h.type==='block'){if(h.hp<=0)return;ctx.save();ctx.translate(h.x,h.y);if(images.defenseWall.complete)ctx.drawImage(images.defenseWall,-h.w/2,-h.h/2,h.w,h.h);ctx.fillStyle='#102033e8';round(-25,-12,50,24,6);ctx.fill();ctx.strokeStyle='#ffcb31';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#fff';ctx.font='900 18px Rajdhani';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(Math.max(0,Math.ceil(h.hp)),0,1);ctx.restore();return}if(h.type==='door'){const im=images.metalGate,doorW=h.w+26,doorH=74,slide=h.open?h.w*.31:0;ctx.save();ctx.translate(h.x,h.y);if(im.complete){const half=im.naturalWidth/2;ctx.drawImage(im,0,0,half,im.naturalHeight,-doorW/2-slide,-doorH/2,doorW/2,doorH);ctx.drawImage(im,half,0,half,im.naturalHeight,slide,-doorH/2,doorW/2,doorH)}ctx.fillStyle=h.open?'#55ff9a':'#ffcf32';ctx.font='900 12px Rajdhani';ctx.textAlign='center';ctx.fillText(h.open?'APERTA':'CHIUSA',0,-doorH/2-7);ctx.restore();return}hazard(h)}
function worldObjects(){for(const d of state.decorations){const y=(d.y+state.time*28)%(H+150)-75;sprite(images[d.type],d.x,y,d.size,Math.sin(state.time+d.y)*.05)}const o=state.divider;ctx.fillStyle='#263241';round(o.x-o.w/2,o.y-o.h/2,o.w,o.h,13);ctx.fill();ctx.strokeStyle='#ffcc26';ctx.lineWidth=5;ctx.stroke();for(let y=o.y-o.h/2+24;y<o.y+o.h/2;y+=42)sprite(images.barrier,o.x,y,48)}
const legacyHazard=hazard;hazard=h=>h.type==='block'||h.type==='door'?assetHazard(h):legacyHazard(h);
function sprite(im,x,y,size,rot=0){if(!im?.complete)return;ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.drawImage(im,-size/2,-size/2,size,size);ctx.restore()}
function draw(){road();if(!state)return;worldObjects();state.hazards.forEach(hazard);const b=state.boss;ctx.fillStyle='#ffae00';round(W/2-55,8,110,78,14);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.stroke();if(!b.active){ctx.fillStyle='#fff';ctx.font='900 42px Rajdhani';ctx.textAlign='center';ctx.fillText('?',W/2,61)}if(b.active){ctx.fillStyle='#17203355';ctx.beginPath();ctx.ellipse(b.x,b.y+30,38,11,0,0,7);ctx.fill();const bossBob=Math.sin(state.time*5)*4,bossTilt=Math.sin(state.time*3)*.045;sprite(images[b.type],b.x,b.y+bossBob,b.hit>0?88:80,bossTilt)}state.enemies.forEach(e=>unit(e,true));state.gates.forEach(gate);state.crates.forEach(crate);state.units.forEach(u=>unit(u));ctx.save();ctx.translate(state.cannon.x,state.cannon.y);ctx.fillStyle='#06396a';ctx.beginPath();ctx.arc(0,18,38,0,7);ctx.fill();ctx.strokeStyle=state.cannon.evolution?'#fff34d':'#50eaff';ctx.lineWidth=5;ctx.shadowBlur=state.cannon.evolution?22:0;ctx.shadowColor='#ffe82e';ctx.stroke();ctx.restore();ctx.save();ctx.shadowBlur=state.cannon.evolution?24:0;ctx.shadowColor='#ffe82e';sprite(images[['gun1','gun2','gun3'][state.cannon.weapon]],state.cannon.x,state.cannon.y-4,78+state.cannon.evolution*5,-Math.PI/2);ctx.restore();ctx.fillStyle='#081b34dd';round(state.cannon.x-43,state.cannon.y+26,86,25,10);ctx.fill();ctx.fillStyle=state.cannon.evolution?'#fff34d':'#fff';ctx.font='900 14px Rajdhani';ctx.textAlign='center';ctx.fillText(`EVOLUZIONE ${state.cannon.evolution}`,state.cannon.x,state.cannon.y+44);for(const p of state.particles){ctx.globalAlpha=p.life/p.max;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()}for(const t of state.texts){ctx.globalAlpha=t.life/t.max;ctx.fillStyle=t.color;ctx.font='900 25px Rajdhani';ctx.fillText(t.value,t.x,t.y)}ctx.globalAlpha=1}
function finish(won){const end=$('#end');$('#end small').textContent=won?'BASE CONQUISTATA':'ESERCITO ESAURITO';$('#end h1').innerHTML=won?'VITTORIA!':'RIPROVA';$('#result').textContent=won?`Hai sconfitto il boss del livello ${state.level}. La prossima battaglia sarà più difficile.`:'Scegli il portale migliore e crea una folla abbastanza grande da superare l’esercito rosso.';$('#again').textContent=won?'LIVELLO SUCCESSIVO':'RIPETI LIVELLO';end.classList.remove('hidden')}
function victorySequence(){if(!state?.won)return;const overlay=$('#countdown'),steps=['3','2','1','VITTORIA!'];let i=0;overlay.textContent=steps[0];overlay.classList.remove('hidden');const timer=setInterval(()=>{i++;if(i<steps.length){overlay.textContent=steps[i];overlay.style.animation='none';void overlay.offsetWidth;overlay.style.animation='pop .65s ease'}else{clearInterval(timer);overlay.classList.add('hidden');reset(state.level+1)}},850)}

function start(next=false){ensureAudio();if(audio && !musicMuted) audio.element.play();$('#start').classList.add('hidden');$('#end').classList.add('hidden');
    $('#pause-menu').classList.add('hidden');reset(next&&state?.won?state.level+1:(state?.level||1))}
  
function pauseGame(show=true){if(!state?.running)return;state.paused=show;$('#pause-menu').classList.toggle('hidden',!show)}
document.querySelectorAll('[data-difficulty]').forEach(button=>button.onclick=()=>{difficulty=button.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(b=>b.classList.toggle('active',b===button))});
$('#language').onchange=e=>{language=e.target.value;applyLanguage()};$('#play').onclick=()=>start(false);$('#again').onclick=()=>start(true);$('#pause').onclick=()=>pauseGame(true);$('#resume').onclick=()=>pauseGame(false);$('#restart').onclick=()=>{const level=state?.level||1;$('#pause-menu').classList.add('hidden');reset(level)};$('#home').onclick=()=>{if(state)state.running=false;state=null;$('#pause-menu').classList.add('hidden');$('#end').classList.add('hidden');$('#countdown').classList.add('hidden');$('#start').classList.remove('hidden');ui.boss.classList.add('hidden')};$('#music').onclick=toggleMusic;$('#power').onclick=launchGiant;addEventListener('keydown',e=>{if(e.code==='Escape'&&state?.running)pauseGame(!state.paused);if(e.code==='Space'){e.preventDefault();launchGiant()}});applyLanguage();function loop(t){const dt=Math.min(.032,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
